# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./FrontEnd:/app
    command: npm run dev

  ginserver:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - 5000:5000
    volumes:
      - ./BackEnd:/app
    command: bash /app/Start.sh
    links:
      - db

  web:
    image: nginx
    volumes:
      - ./docker/init/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    links:
      - "nextjs"
      - "ginserver"
